from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum


# ─────────────────────────────────────────────────────────────────────────────
# Arc Shape Types  (NEW — Dynamic Intelligence Layer)
# ─────────────────────────────────────────────────────────────────────────────

class ArcShape(Enum):
    """
    The six universal shapes that describe any compelling gaming moment.
    Detected from the mathematical curve of the composite signal — game-agnostic.
    """
    SPIKE     = "spike"      # Sudden sharp peak — kill, explosion, jump scare
    TENSION   = "tension"    # Slow rise → sustained plateau → sudden drop — chase, stealth, standoff
    COMEDY    = "comedy"     # Long quiet → unexpected multi-signal spike — fail, funny NPC
    DRAMA     = "drama"      # High speech + emotion sustained, low motion — dialogue, cutscene
    TRIUMPH   = "triumph"    # Oscillating struggle → sustained high at end — boss kill, clutch win
    DISCOVERY = "discovery"  # All signals shift character simultaneously — new area, plot reveal


# Clip duration rules per arc shape (min_secs, max_secs)
ARC_DURATION_RULES: Dict[str, tuple] = {
    ArcShape.SPIKE.value:     (5,  35),
    ArcShape.TENSION.value:   (20, 90),
    ArcShape.COMEDY.value:    (6,  30),
    ArcShape.DRAMA.value:     (10, 75),
    ArcShape.TRIUMPH.value:   (15, 75),
    ArcShape.DISCOVERY.value: (8,  45),
}

# Human-readable labels for GUI display
ARC_SHAPE_LABELS: Dict[str, str] = {
    ArcShape.SPIKE.value:     "Action Moment",
    ArcShape.TENSION.value:   "Suspense Arc",
    ArcShape.COMEDY.value:    "Comedy Beat",
    ArcShape.DRAMA.value:     "Dramatic Scene",
    ArcShape.TRIUMPH.value:   "Triumph Moment",
    ArcShape.DISCOVERY.value: "Discovery Moment",
}


@dataclass
class ArcRegion:
    """
    A contiguous region of the timeline where signals are elevated above baseline.
    The shape_type describes the mathematical pattern of that elevation.
    """
    shape_type: ArcShape
    start: float                     # seconds
    end: float                       # seconds
    peak_time: float                 # timestamp of maximum composite signal
    quality_score: float             # 0.0-1.0  overall arc quality
    composite_values: List[float]    # per-second composite signal within the arc
    peak_audio: float = 0.0
    peak_motion: float = 0.0
    peak_emotion: float = 0.0
    peak_speech: float = 0.0
    end_composite: float = 0.0       # composite value at arc end (for tension resolution check)
    transcript: str = ""
    label: str = ""                  # enriched by GameAdapter
    clip_prompt: str = ""            # enriched by GameAdapter (for CLIP visual scoring)
    hook_sentence: str = ""          # generated by NarrativeEngine LLM
    short_title: str = ""            # generated by NarrativeEngine LLM

    @property
    def duration(self) -> float:
        return self.end - self.start

    def to_clipper_json(self) -> Dict:
        min_dur, max_dur = ARC_DURATION_RULES.get(self.shape_type.value, (5, 60))
        return {
            "start": round(self.start, 3),
            "end": round(self.end, 3),
            "peak_time": round(self.peak_time, 3),
            "shape_type": self.shape_type.value,
            "category": ARC_SHAPE_LABELS.get(self.shape_type.value, "Highlight"),
            "score": int(self.quality_score * 100),
            "rank_score": round(self.quality_score, 4),
            "reason": self.label or ARC_SHAPE_LABELS.get(self.shape_type.value, "Arc"),
            "text": self.transcript,
            "hook": self.hook_sentence,
            "title": self.short_title,
            "events": [self.shape_type.value],
            "evidence": {
                "peak_audio": round(self.peak_audio, 3),
                "peak_motion": round(self.peak_motion, 3),
                "peak_emotion": round(self.peak_emotion, 3),
                "peak_speech": round(self.peak_speech, 3),
                "end_composite": round(self.end_composite, 3),
            }
        }


@dataclass
class GameProfile:
    game_id: str
    game_name: str
    genre: str
    priority_events: List[str]
    ignore_states: List[str]
    context_rules: Dict[str, float]
    score_weights: Dict[str, float]
    event_rules: List[Dict[str, Any]]
    spatial_rules: Dict[str, Any] = field(default_factory=dict)
    audio_weights: Optional[Dict[str, float]] = None
    transitions: Optional[Dict[str, Any]] = None
    version: str = "1.0.0"

    @classmethod
    def from_json(cls, data: Dict[str, Any]):
        return cls(
            game_id=data.get("game_id", "generic"),
            game_name=data.get("game_name", "Generic Game"),
            genre=data.get("genre", "general"),
            priority_events=data.get("priority_events", []),
            ignore_states=data.get("ignore_states", []),
            context_rules=data.get("context_rules", {}),
            score_weights=data.get("score_weights", {}),
            event_rules=data.get("event_rules", []),
            spatial_rules=data.get("spatial_rules", {}),
            audio_weights=data.get("audio_weights"),
            transitions=data.get("transitions"),
            version=data.get("version", "1.0.0")
        )

@dataclass
class TimelineSecond:
    timestamp: float
    speech_score: float = 0.0
    audio_score: float = 0.0
    visual_score: float = 0.0
    emotion_score: float = 0.0
    detect_scores: Dict[str, float] = field(default_factory=dict)
    is_ignore_state: bool = False
    ignore_reason: Optional[str] = None
    fused_score: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class DetectedEvent:
    event_type: str
    timestamp: float
    score: float
    evidence: Dict[str, Any] = field(default_factory=dict)
    duration: float = 1.0

@dataclass
class HighlightCandidate:
    start: float
    end: float
    anchor_event: DetectedEvent
    score: float
    category: str
    reason: str
    game_id: str
    events: List[DetectedEvent] = field(default_factory=dict)
    profile_id: str = ""
    profile_version: str = ""
    evidence: Dict[str, Any] = field(default_factory=dict)
    text: str = ""
    rank_score: float = 0.0  # Blended score used for final ranking

    def to_clipper_json(self):
        return {
            "start": round(self.start, 3),
            "end": round(self.end, 3),
            "peak_time": round(self.anchor_event.timestamp, 3),
            "category": self.category,
            "score": int(self.score * 100),
            "rank_score": round(self.rank_score, 4),
            "reason": self.reason,
            "text": self.text,
            "game": self.game_id,
            "events": [e.event_type for e in self.events],
            "profile_id": self.profile_id,
            "profile_version": self.profile_version,
            "evidence": self.evidence
        }
